apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-spring-boot-app
  namespace: eks-work
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: user-spring-boot-app
  template:
    metadata:
      labels:
        app: user-spring-boot-app
    spec:
      nodeName: ip-192-168-0-138.ap-northeast-2.compute.internal
      containers:
        - name: user-spring-boot
          image: 354918381360.dkr.ecr.ap-northeast-2.amazonaws.com/ssafy/edith:user-spring-boot-app-76
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 30
          env:
            - name: SPRING_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: SPRING_JWT_SECRET

---

apiVersion: v1
kind: Service
metadata:
  name: user-spring-boot-service
  namespace: eks-work
spec:
  type: NodePort
  ports:
    - port: 8181
      targetPort: 8081
      nodePort: 32081 
  selector:
    app: user-spring-boot-app