apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mysql
  namespace: eks-work2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-mysql
  template:
    metadata:
      labels:
        app: user-mysql
    spec:
      nodeName: ip-192-168-1-75.ap-northeast-2.compute.internal
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "ssafy"
            - name: MYSQL_DATABASE
              value: "user_database"
            - name: MYSQL_USER
              value: "edith"
            - name: MYSQL_PASSWORD
              value: "ssafy"
          ports:
            - containerPort: 3306
