apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-t3xlarge
  namespace: eks-work
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-t3xlarge
  template:
    metadata:
      labels:
        app: nginx-t3xlarge
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: group
                operator: In
                values:
                - t3xlarge
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-config-t3xlarge
        - mountPath: /etc/nginx/certs  # 인증서가 마운트될 경로
          name: tls-certs
          readOnly: true
        ports:
        - containerPort: 80
        - containerPort: 443  # HTTPS 포트 추가
      volumes:
      - name: nginx-config-t3xlarge
        configMap:
          name: nginx-config-t3xlarge
      - name: tls-certs
        secret:
          secretName: letsencrypt-tls  # 생성한 Secret 이름
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-t3xlarge
  namespace: eks-work
spec:
  type: NodePort
  selector:
    app: nginx-t3xlarge
  ports:
    - name: http
      protocol: TCP
      port: 80           # Nginx HTTP 포트
      targetPort: 80
      nodePort: 30080    # 외부 노출 HTTP NodePort
    - name: https
      protocol: TCP
      port: 443          # Nginx HTTPS 포트
      targetPort: 443
      nodePort: 30443    # 외부 노출 HTTPS NodePort