spring:
  application:
    name: developmentassistant
  datasource:
    url: jdbc:mysql://developmentassistant-mysql-clusterip.eks-work2.svc.cluster.local:3306/developmentassistant_database
    username: edith
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: redis-clusterip.eks-work2.svc.cluster.local
      port: 6379
server:
  port: 8082
