spring:
  application:
    name: developmentassistant

  profiles:
    active: prod

  datasource:
    url: jdbc:mysql://developmentassistant-mysql-clusterip.eks-work2.svc.cluster.local:3307/developmentassistant_database
    username: edith
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8082
