spring:
  application:
    name: developmentassistant

  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console


server:
  port: 8082

api:
  flask:
    portfolio: http://rag-flask-service:8183/rag/portfolio
#    portfolio: http://localhost:8083/rag/portfolio # 로컬
    code-review: http://rag-flask-service:8183/rag/code-review
    rag : http://rag-flask-service:8183/rag

