apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetest
  labels:
    app: kubetest
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: kubetest
  template:
    metadata:
      labels:
        app: kubetest
    spec:
      containers:
      - name: kubetest
        image: 354918381360.dkr.ecr.ap-northeast-2.amazonaws.com/ssafy/edith:kubetest-spring-boot-app-34
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        readinessProbe:
          httpGet:
            port: 9090
            path: /test
          initialDelaySeconds: 15
          periodSeconds: 30
        livenessProbe:
          httpGet:
            port: 9090
            path: /test
          initialDelaySeconds: 15
          periodSeconds: 30          
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 2"]        

---

apiVersion: v1
kind: Service
metadata:
  name: kubetest
  labels:
    app: kubetest
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 9190        # 클러스터 내부에서 사용하는 서비스 포트
    targetPort: 9090  # Pod의 컨테이너 포트
    nodePort: 30688   # 외부에서 노드의 IP와 함께 접근할 때 사용할 고정 포트 번호
  selector:
    app: kubetest
