spring:
  application:
    name: user
  jwt:
    secret: ${SPRING_JWT_SECRET}
    access-token-expiration: 3600000
    refresh-token-expiration: 86400000
  datasource:
    url: jdbc:mysql://localhost:3306/user_database # url 수정예정
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: k11c206.p.ssafy.io
      port: 6379

server:
  port: 8081

app:
  cookie:
    expiration: 86400