spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://user-mysql-clusterip.eks-work2.svc.cluster.local:3306/user_database
    username: edith
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jwt:
    secret: ${SPRING_JWT_SECRET}
    access-token-expiration: 3600000
    refresh-token-expiration: 86400000
  data:
    redis:
      host: redis-clusterip.eks-work2.svc.cluster.local
      port: 6379

server:
  port: 8081
app:
  cookie:
    expiration: 3600

fastapi:
  url: http://face-recognition-fastapi-app:8184

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info
