frontend:
  servers:
    - "http://localhost:5173"
    - "http://k11c206.p.ssafy.io:3000"

spring:
  application:
    name: SCG
  jwt:
    secret: ${SPRING_JWT_SECRET}
  cloud:
    gateway:
      routes:
        - id: user-test
          uri: http://user-spring-boot-service:8181
          predicates:
            - Path=/api/v1/users/test
          filters:
            - name: JwtAuthFilter

        - id: user-validate
          uri: http://user-spring-boot-service:8181
          predicates:
            - Path=/api/v1/users/validate
          filters:
            - name: JwtAuthFilter

        - id: user-api
          uri: http://user-spring-boot-service:8181
          predicates:
            - Path=/api/v1/users/**

        - id: user-websocket
          uri: ws://user-fastapi-service:8184
          predicates:
            - Path=/ws/users/face_recognition

        - id: developmentassistant-projects-api
          uri: http://developmentassistant-spring-boot-service:8182
          predicates:
            - Path=/api/v1/projects/**

        - id: developmentassistant-portfolio-api
          uri: http://developmentassistant-spring-boot-service:8182
          predicates:
            - Path=/api/v1/portfolio/**

        - id: face-recognition-api
          uri: http://face-recognition-fastapi-service:8184
          predicates:
            - Path=/api/v1/face-recognition/**

        - id: kubetest
          uri: http://kubetest:9190
          predicates:
            - Path=/test
server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: debug

management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, gateway