frontend:
  servers:
    - "http://localhost:5173"
    - "http://k11c206.p.ssafy.io:3000"

spring:
  application:
    name: SCG
  cloud:
    gateway:
      routes:
        - id: user-test
          uri: http://localhost:8081 # User 서버 주소
          predicates:
            - Path=/api/v1/users/test
          filters:
            - name: JwtAuthFilter

        - id: user
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**


  jwt:
    secret: ${SPRING_JWT_SECRET}
    access-token-expiration: 3600000
    refresh-token-expiration: 604800000

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: debug

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
