frontend:
  servers:
    - "http://localhost:5173"
    - "http://k11c206.p.ssafy.io:3000"

spring:
  application:
    name: SCG
  jwt:
    secret: ${SPRING_JWT_SECRET}
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://k11c206.p.ssafy.io:8081
          predicates:
            - Path=/api/v1/users/**

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: debug

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway