apiVersion: apps/v1
kind: Deployment
metadata:
  name: developmentassistant-spring-boot-app
  namespace: eks-work
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: developmentassistant-spring-boot-app
  template:
    metadata:
      labels:
        app: developmentassistant-spring-boot-app
    spec:
      containers:
        - name: developmentassistant-spring-boot-app
          image: 354918381360.dkr.ecr.ap-northeast-2.amazonaws.com/ssafy/edith:developmentassistant-spring-boot-app-48
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          # env:
          #   - name: QDRANT_HOST
          #     value: "qdrant.eks-work2.svc.cluster.local"  # Qdrant의 ClusterIP 주소
          #   - name: QDRANT_PORT
          #     value: "6333"
          #   - name: JWT_SECRET
          #     valueFrom:
          #       secretKeyRef:
          #         name: jwt-secret
          #         key: SPRING_JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: developmentassistant-spring-boot-service
  namespace: eks-work
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8182
      targetPort: 8082
      nodePort: 32082
  selector:
    app: developmentassistant-spring-boot-app

