apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  namespace: eks-work2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:latest
          ports:
            - containerPort: 6333
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: eks-work2
spec:
  selector:
    app: qdrant
  ports:
    - protocol: TCP
      port: 6333
      targetPort: 6333
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-nodeport
  namespace: eks-work2
spec:
  selector:
    app: qdrant
  ports:
    - protocol: TCP
      port: 6333
      targetPort: 6333
      nodePort: 30333
  type: NodePort
