apiVersion: v1
kind: Service
metadata:
  name: user-mysql
  namespace: eks-work2
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30036
  selector:
    app: user-mysql